### ISSUE TITLE
Add long answer text input to forms 

### ISSUE THREAD

**Issue by sherryyx** [nwhacks/nwhacks2018_static#9]
We want to encourage applicants to write more in their long answer responses

See figma file: https://www.figma.com/file/O3fGShcZs55Nbxwe65lTKrE5/nwHacks.io

Thanks!

**Comment by d4l3k** [comment]
![2017-10-27-210159_497x386_scrot](https://user-images.githubusercontent.com/909104/32131148-621db412-bb5b-11e7-886c-e4683fb9dd30.png)
![2017-10-27-210137_478x335_scrot](https://user-images.githubusercontent.com/909104/32131149-6236bd5e-bb5b-11e7-809c-c8d7687f6df2.png)

I made the areas bigger since that was really quick. I can add the colored borders but it'll take longer

**Comment by d4l3k** [comment]
I can make the areas even bigger if you'd like. They're currently set to 4 lines

**Comment by luceliu** [comment]
<img width="710" alt="screen shot 2017-10-30 at 8 45 30 pm" src="https://user-images.githubusercontent.com/20194766/32206720-16f0755a-bdb4-11e7-95c8-266fd2428f48.png">
Could we get the green line to sit right under the final line of input text? @d4l3k

**Comment by d4l3k** [comment]
That's kind of a bitch to do, might get to this later
